config/routes.rb
Rails.application.routes.draw do
scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
  root 'homes#top'

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    patch 'withdrawal' => 'users#withdrawal'
  end

  resources :posts, only: [:index, :show, :create, :destroy] do
    resources :post_comments

    resource :favorites, only: [:create, :destroy]
  end

  resources :tag, only: [] do
    get 'posts', to: 'posts#search'
  end

  resources :areas, only: [:index, :show]
  get 'search_city/:id', to: 'areas#search', as: :search_city
  
  namespace :admin do
    resources :users, only: [:index, :edit, :update]
  end
  
  get 'searches' => 'searches#search'
  
  
    
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  def following?(user)
    followings.include?(user)
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def active_for_authentication?
    super && self.status == false
  end
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.name = "ゲスト"
      user.prefecture = "東京都"
      user.cities = "千代田区"
      user.password = SecureRandom.urlsafe_base64
    end
  end


  attachment :user_image, destroy: false
  validates :name, length: {maximum: 30, minimum: 2}, uniqueness: true
  validates :prefecture, presence: true
  validates :cities, presence: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    user = User.find(params[:id])
    user.update(admin_user_params)
    redirect_to admin_users_path
  end
  
  private
  
  def admin_user_params
    params.require(:user).permit(:status)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  
  def create
    super
    if resource.persisted?
      UserMailer.welcome_email(params[:user][:email], params[:user][:name]).deliver
    end
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path
  end
  
  
  
  protected
  
  def reject_user
    user = User.find_by(email: params[:user][:email].downcase)
    if user
      if (user.valid_password?(params[:user][:password]) && (user.active_for_authentication? == true))
        redirect_to new_user_session_path
      end
    end
  end
  
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @post = Post.new
  end

  def index
    @user = current_user
    @users = User.all
    @post = Post.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def withdrawal
    user = User.find(params[:user_id])
    unless user.email == "guest@example.com"
      user.update(status: true)
      reset_session
    end

    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :user_image)
  end
  
  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.slim
- if current_user.following?(user)
    = link_to t('UnFollow'), user_relationships_path(user.id), remote: true, method: :delete, class: "btn btn-danger rounded-pill"
-else
    = link_to t('Follow'), user_relationships_path(user.id), remote: true, method: :post, class: "btn btn-primary rounded-pill"

app/views/users/index.html.slim
div.container.px-5.px-sm-0
  div.row
    div.col-md-3
        h2
          = t('User list')

        = link_to edit_user_registration_path
          = attachment_image_tag @user, :user_image, :fill, 100, 100, fallback: "no_image_square.jpg", size:"100x100", class: "rounded-circle"

        h5
          = t('Post form')
        == render 'posts/form', post: @post, user: @user

    div.col-md-9
      div.row
        - @users.each do |user|
            div.col-md-4
              div.card.user-show-img.h-100 id='user_#{ user.id }'
                = link_to user_path(user)
                  = attachment_image_tag user, :user_image,  fallback: "no_image_square.jpg", class: "card-img user-img-h"
                span.user-follow
                  - if user.id == current_user.id
                  - else
                    p id='user_#{ user.id }_follow-btn'
                      == render 'users/follow', user: user
                span.card-title
                  = user.name
                span.card-text
                  = link_to user_followings_path(user.id)
                    p id='user_#{ user.id }_follow'
                      = t('follow number')
                      | #{user.followings.count}

                  = link_to user_followers_path(user.id)
                    p id='user_#{ user.id }_follower'
                      = t('followed number')
                      | #{user.followers.count}

app/views/users/show.html.slim
div.container.px-5.px-sm-0
  div.row
    div.col-md-3
      -if @user == current_user
        h2
          = t('My page')

      - else
        h2
          | #{@user.name}
          = t('nopage')

      - if @user == current_user
        = link_to edit_user_registration_path
          = attachment_image_tag @user, :user_image, :fill, 100, 100, fallback: "no_image_square.jpg", size:"100x100", class: "rounded-circle"
      - else
        = attachment_image_tag @user, :user_image, :fill, 100, 100, fallback: "no_image_square.jpg", size:"100x100", class: "rounded-circle"
        
      - if @user == current_user
          h5
            = t('Post form')
          == render 'posts/form', post: @post, user: @user

    div.col-md-8.offset-md-1.text-center.user-post-index
      - @posts.each do |post|
        div.card.user-show-img
          = link_to post_path(post)
            = attachment_image_tag post, :post_image, :fill, 300, 200,  class: "card-img"
          div.dropdown.user-show-del
            span class="fas fa-ellipsis-h"  id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false"
            ul class="dropdown-menu" aria-labelledby="dropdownMenuButton"
              li
                = link_to t('Delete'), post_path(post.id), method: :delete, class: "dropdown-item"

          br

          span.card-title.user-span
            - post.taggings.each do |tag|
              = link_to tag_posts_path(tag_id: tag.tag.id), class: "btn btn-sm btn-secondary user-tag-link"
                p.usershowtag
                  | #{tag.tag.category}
          p
            = post.body