config/routes.rb
Rails.application.routes.draw do
scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
  root 'homes#top'

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    patch 'withdrawal' => 'users#withdrawal'
  end

  resources :posts, only: [:index, :show, :create, :destroy] do
    resources :post_comments

    resource :favorites, only: [:create, :destroy]
  end

  resources :tag, only: [] do
    get 'posts', to: 'posts#search'
  end

  resources :areas, only: [:index, :show]
  get 'search_city/:id', to: 'areas#search', as: :search_city
  
  namespace :admin do
    resources :users, only: [:index, :edit, :update]
  end
  
  get 'searches' => 'searches#search'
  
  
    
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :prefecture
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  attachment :post_image

  has_many :post_comments, dependent: :destroy
  has_many :favorites
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def save_tag(post, sent_tags, flag)
    sent_tags.each do |tag|
      if flag == 1
        tag = Translation.get_translate_data(tag)
      end
      get_tag = Tag.find_or_create_by(category: tag)
      Tagging.create(post_id: post.id, tag_id: get_tag.id)
      # unless Tag.find_by(category: tag)
      #   Tag.create(category: tag)
      #   new_tag = Tag.find_by(category: tag)
      #   Tagging.create(post_id: post.id, tag_id: new_tag.id)
      # else
      #   exist_tag = Tag.find_by(category: tag)
      #   Tagging.create(post_id: post.id, tag_id: exist_tag.id)
      # end
    end
  end
  
  # def save_tag_api(post, sent_tags)
  #   sent_tags.each do |tag|
  #     tag = Translation.get_translate_data(tag)
  #     get_tag = Tag.find_or_create_by(category: tag)
  #     Tagging.create(post_id: post.id, tag_id: get_tag.id)
  #   end
  # end
  
  validates :post_image, presence: true
  validates :prefecture, presence: true
  validates :cities, presence: true
  validates :body, presence: true, length: {maximum: 200}

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
  validates :comment, presence: true, length: {maximum: 200}
  
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :cities
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings
  
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  def following?(user)
    followings.include?(user)
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def active_for_authentication?
    super && self.status == false
  end
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.name = "ゲスト"
      user.prefecture = "東京都"
      user.cities = "千代田区"
      user.password = SecureRandom.urlsafe_base64
    end
  end


  attachment :user_image, destroy: false
  validates :name, length: {maximum: 30, minimum: 2}, uniqueness: true
  validates :prefecture, presence: true
  validates :cities, presence: true
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
  
  def show
    prefecture = Prefecture.find(params[:id])
    @cities = prefecture.cities
  end
  
  def search
    city = City.find(params[:id])
    @posts = Post.where(cities: city.name)
    @user = current_user
    @post = Post.new
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:destroy]

  def index
    @posts = Post.all
    @post = Post.new
    @user = current_user
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @post_comment = PostComment.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    tag_list = params[:post][:category].split(nil)
    if @post.save
      @post.save_tag(@post, tag_list, 0)
      tag_api = Vision.get_image_data(@post.post_image)
      @post.save_tag(@post, tag_api, 1)
      # tag_list.each do |tag_name|
      #   tag = Tag.find_by(category: tag_name)
      #   Tagging.create(post_id: @post.id, tag_id: tag.id)
      # end
      redirect_to request.referer
    else
      redirect_to request.referer
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to request.referer
  end

  def search
    @user = current_user
    @tag = Tag.find(params[:tag_id])
    @posts = @tag.posts
  end


  private

  def post_params
    params.require(:post).permit(:post_image, :prefecture, :cities, :body)
  end

  def ensure_correct_user
    @post = Post.find(params[:id])
    unless @post.user == current_user
      redirect_to posts_path
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/areas/index.html.slim
= image_tag asset_path('22018625.jpg'), usemap: "#image-map", class: "map d-block mx-auto"

map name="image-map"
  =link_to area_path(1)
    area target="_blank" alt="北海道" title="北海道" coords="2842,604,2315,175" shape="rect"
  =link_to area_path(2)
    area target="_blank" alt="青森" title="青森" href="#" coords="2310,721,2747,996" shape="rect"
  =link_to area_path(3)
    area target="_blank" alt="岩手" title="岩手" href="#" coords="2572,1018,2744,1261" shape="rect"
  =link_to area_path(4)
    area target="_blank" alt="宮城" title="宮城" href="#" coords="2601,1283,2742,1500" shape="rect"
  =link_to area_path(5)
    area target="_blank" alt="秋田" title="秋田" href="#" coords="2315,1018,2545,1259" shape="rect"
  =link_to area_path(6)
    area target="_blank" alt="山形" title="山形" href="#" coords="2318,1288,2577,1503" shape="rect"
  =link_to area_path(7)
    area target="_blank" alt="福島" title="福島" href="#" coords="2432,1521,2742,1701" shape="rect"
  =link_to area_path(8)
    area target="_blank" alt="茨城" title="茨城" href="#" coords="2598,1723,2744,1937" shape="rect"
  =link_to area_path(9)
    area target="_blank" alt="栃木" title="栃木" href="#" coords="2434,1723,2575,1935" shape="rect"
  =link_to area_path(10)
    area target="_blank" alt="群馬" title="群馬" href="#" coords="2275,1723,2410,1935" shape="rect"
  =link_to area_path(11)
    area target="_blank" alt="埼玉" title="埼玉" href="#" coords="2357,1958,2535,2041" shape="rect"
  =link_to area_path(12)
    area target="_blank" alt="千葉" title="千葉" href="#" coords="2601,1958,2747,2147" shape="rect"
  =link_to area_path(13)
    area target="_blank" alt="東京" title="東京" href="#" coords="2357,2059,2535,2136" shape="rect"
  =link_to area_path(14)
    area target="_blank" alt="神奈川" title="神奈川" href="#" coords="2357,2160,2538,2245" shape="rect"
  =link_to area_path(15)
    area target="_blank" alt="新潟" title="新潟" href="#" coords="1994,1521,2410,1701" shape="rect"
  =link_to area_path(16)
    area target="_blank" alt="富山" title="富山" href="#" coords="1835,1553,1973,1670" shape="rect"
  =link_to area_path(17)
    area target="_blank" alt="石川" title="石川" href="#" coords="1705,1436,1814,1720" shape="rect"
  =link_to area_path(18)
    area target="_blank" alt="福井" title="福井" href="#" coords="1507,1619,1689,1723" shape="rect"
  =link_to area_path(19)
    area target="_blank" alt="山梨" title="山梨" href="#" coords="2169,1956,2339,2064" shape="rect"
  =link_to area_path(20)
    area target="_blank" alt="長野1" title="長野1" href="#" coords="1992,2064,2153,1720" shape="rect"
  =link_to area_path(20)
    area target="_blank" alt="長野2" title="長野2" href="#" coords="2254,1720,2156,1940" shape="rect"
  =link_to area_path(21)
    area target="_blank" alt="岐阜1" title="岐阜1" href="#" coords="1766,1741,1973,2064" shape="rect"
  =link_to area_path(21)
    area target="_blank" alt="岐阜2" title="岐阜2" href="#" coords="1830,1686,1973,1736" shape="rect"
  =link_to area_path(22)
    area target="_blank" alt="静岡" title="静岡" href="#" coords="1989,2080,2339,2250" shape="rect"
  =link_to area_path(23)
    area target="_blank" alt="愛知" title="愛知" href="#" coords="1766,2080,1973,2250" shape="rect"
  =link_to area_path(24)
    area target="_blank" alt="三重" title="三重" href="#" coords="1578,1943,1745,2319" shape="rect"
  =link_to area_path(25)
    area target="_blank" alt="滋賀" title="滋賀" href="#" coords="1583,1739,1745,1927" shape="rect"
  =link_to area_path(26)
    area target="_blank" alt="京都" title="京都" href="#" coords="1406,1739,1562,1924" shape="rect"
  =link_to area_path(27)
    area target="_blank" alt="大阪" title="大阪" href="#" coords="1364,1943,1422,2155" shape="rect"
  =link_to area_path(28)
    area target="_blank" alt="兵庫" title="兵庫" href="#" coords="1212,1741,1387,1924" shape="rect"
  =link_to area_path(29)
    area target="_blank" alt="奈良" title="奈良" href="#" coords="1443,1940,1562,2157" shape="rect"
  =link_to area_path(30)
    area target="_blank" alt="和歌山" title="和歌山" href="#" coords="1326,2173,1560,2319" shape="rect"
  =link_to area_path(31)
    area target="_blank" alt="鳥取" title="鳥取" href="#" coords="1019,1736,1191,1821" shape="rect"
  =link_to area_path(32)
    area target="_blank" alt="島根" title="島根" href="#" coords="833,1736,1000,1823" shape="rect"
  =link_to area_path(33)
    area target="_blank" alt="岡山" title="岡山" href="#" coords="1022,1839,1194,1924" shape="rect"
  =link_to area_path(34)
    area target="_blank" alt="広島" title="広島" href="#" coords="831,1839,1000,1924" shape="rect"
  =link_to area_path(35)
    area target="_blank" alt="山口" title="山口" href="#" coords="701,1739,810,1924" shape="rect"
  =link_to area_path(36)
    area target="_blank" alt="徳島" title="徳島" href="#" coords="1085,2099,1194,2192" shape="rect"
  =link_to area_path(37)
    area target="_blank" alt="香川" title="香川" href="#" coords="953,2102,1067,2189" shape="rect"
  =link_to area_path(38)
    area target="_blank" alt="愛媛" title="愛媛" href="#" coords="749,2104,934,2189" shape="rect"
  =link_to area_path(39)
    area target="_blank" alt="高知" title="高知" href="#" coords="749,2210,1194,2298" shape="rect"
  =link_to area_path(40)
    area target="_blank" alt="福岡" title="福岡" href="#" coords="327,1778,476,2001" shape="rect"
  =link_to area_path(41)
    area target="_blank" alt="佐賀" title="佐賀" href="#" coords="242,1781,309,2001" shape="rect"
  =link_to area_path(42)
    area target="_blank" alt="長崎" title="長崎" href="#" coords="158,1781,221,2001" shape="rect"
  =link_to area_path(43)
    area target="_blank" alt="熊本" title="熊本" href="#" coords="285,2019,473,2170" shape="rect"
  =link_to area_path(44)
    area target="_blank" alt="大分" title="大分" href="#" coords="494,1778,603,2059" shape="rect"
  =link_to area_path(45)
    area target="_blank" alt="宮崎" title="宮崎" href="#" coords="494,2080,600,2345" shape="rect"
  =link_to area_path(46)
    area target="_blank" alt="鹿児島" title="鹿児島" href="#" coords="285,2189,473,2345" shape="rect"
  =link_to area_path(47)
    area target="_blank" alt="沖縄" title="沖縄" href="#" coords="288,2658,404,2732" shape="rect"

app/views/areas/search.html.slim
div.container.px-5.px-sm-0
  div.row
    div.col-md-3
      h1
        = t('Area search result')

      br
      = link_to edit_user_path(@user)
          = attachment_image_tag @user, :user_image, :fill, 100, 100, fallback: "no_image_square.jpg", size:"100x100", class: "rounded-circle"

      h5
        = t('Post form')
      == render 'posts/form', post: @post, user: @user
    div.col-md-9
      div.row
        - @posts.each do |post|
            div.col-md-4
              div.card.post-index.h-100
                = link_to post_path(post), class: "h-100"
                  = attachment_image_tag post, :post_image, :fill, 300, 200, class: "card-img h-100"
                span id='favorite-#{post.id}'
                  == render "favorites/favorite", post: post

app/views/areas/show.html.slim
div.container.px-5.px-sm-0
  div.row
    - @cities.each do |city|
      div.col-md-2.cityname
        = link_to search_city_path(city.id)
          = city.name

  div.text-center.areasbottun
    =link_to "戻る", areas_path, class: "btn btn-info"

app/views/homes/top.html.slim
div#splash
  div#splash_logo
    = image_tag(asset_path("logo.jpg"),class: "fadeUp logosize")

section.top-section#top1 data-section-name="section1"
  div.top.top-back
    div.d-flex.align-items-center.justify-content-center.link_height
        h1
          | ようこそ Torichanへ
          
    div.text-center
      = link_to "新規登録", new_user_registration_path, class: "btn btn-info btn-lg"

section.top-section#top2 data-section-name="section2"
  div#about.about-back
    div#aboutimages
      div.aboutimage1
        p.about1
          | 鳥の写真を共有するサイトです
          
      div.aboutimage2
        p.about2
          | 知らない鳥に出会った時には情報を共有することができます。
          
          br
          
          | きっと教えてくれる人がいます。
          
          br
          
          | また、地域から投稿を検索することができます。