config/routes.rb
Rails.application.routes.draw do
scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
  root 'homes#top'

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    patch 'withdrawal' => 'users#withdrawal'
  end

  resources :posts, only: [:index, :show, :create, :destroy] do
    resources :post_comments

    resource :favorites, only: [:create, :destroy]
  end

  resources :tag, only: [] do
    get 'posts', to: 'posts#search'
  end

  resources :areas, only: [:index, :show]
  get 'search_city/:id', to: 'areas#search', as: :search_city
  
  namespace :admin do
    resources :users, only: [:index, :edit, :update]
  end
  
  get 'searches' => 'searches#search'
  
  
    
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :prefecture
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  attachment :post_image

  has_many :post_comments, dependent: :destroy
  has_many :favorites
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def save_tag(post, sent_tags, flag)
    sent_tags.each do |tag|
      if flag == 1
        tag = Translation.get_translate_data(tag)
      end
      get_tag = Tag.find_or_create_by(category: tag)
      Tagging.create(post_id: post.id, tag_id: get_tag.id)
      # unless Tag.find_by(category: tag)
      #   Tag.create(category: tag)
      #   new_tag = Tag.find_by(category: tag)
      #   Tagging.create(post_id: post.id, tag_id: new_tag.id)
      # else
      #   exist_tag = Tag.find_by(category: tag)
      #   Tagging.create(post_id: post.id, tag_id: exist_tag.id)
      # end
    end
  end
  
  # def save_tag_api(post, sent_tags)
  #   sent_tags.each do |tag|
  #     tag = Translation.get_translate_data(tag)
  #     get_tag = Tag.find_or_create_by(category: tag)
  #     Tagging.create(post_id: post.id, tag_id: get_tag.id)
  #   end
  # end
  
  validates :post_image, presence: true
  validates :prefecture, presence: true
  validates :cities, presence: true
  validates :body, presence: true, length: {maximum: 200}

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
  validates :comment, presence: true, length: {maximum: 200}
  
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :cities
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings
  
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  def following?(user)
    followings.include?(user)
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def active_for_authentication?
    super && self.status == false
  end
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.name = "ゲスト"
      user.prefecture = "東京都"
      user.cities = "千代田区"
      user.password = SecureRandom.urlsafe_base64
    end
  end


  attachment :user_image, destroy: false
  validates :name, length: {maximum: 30, minimum: 2}, uniqueness: true
  validates :prefecture, presence: true
  validates :cities, presence: true
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
  
  def show
    prefecture = Prefecture.find(params[:id])
    @cities = prefecture.cities
  end
  
  def search
    city = City.find(params[:id])
    @posts = Post.where(cities: city.name)
    @user = current_user
    @post = Post.new
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_language.html.slim
div.dropdown
  span.btn.dropdown-toggle type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
    | language

  div.dropdown-menu aria-labelledby="dropdownMenuLink"
    = link_to('日本語', {:locale => 'ja'}, {class: "dropdown-item"})
    = link_to('English', {:locale => 'en'}, {class: "dropdown-item"})
    = link_to('中文', {:locale => 'zh-TW'}, {class: "dropdown-item"})

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Torichan

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  header class=("header-back-img" if user_signed_in?)
    - if user_signed_in?
      nav.navbar.navbar-expand-sm.p-0
        ul.navbar-nav.mr-auto.d-flex.align-items-center
          li.nav-item.ml-3.mr-3
            = link_to t('My page'), user_path(current_user), class: "headlink"
          li.nav-item.mr-3
            = link_to t('Area search'), areas_path, class: "headlink"
          li.nav-item.mr-3
            = link_to t('User list'), users_path, class: "headlink"
          li.nav-item.mr-3
            = link_to t('Post list'), posts_path, class: "headlink"
          li.nav-item.mr3
            =link_to t('Log out'), destroy_user_session_path, method: :delete, class: "headlink"
        ul.navbar-nav.d-flex.align-items-center
          li.nav-item
            - @guide = "複数のキーワードで検索が出来ます。<br>\
                        複数検索するときはスペースを空けて入力します。<br>\
                        (例) banana lemon <br>\
                        #をつけるとタグを検索します。<br>\
                        (例) #hoge → hogeタグを検索"
            span.fas.fa-question-circle#search-guide data-container="body" data-toggle="popover" data-html="true" data-placement="left" data-content="#{@guide}"

          li.nav-item
            = form_with url: searches_path, method: :get, class: "navbar-nav", local: true do |f|
              = f.text_field :word, placeholder: "\uF002", class: "fa seachicon"
          li.nav-item.pl-2
            == render 'layouts/language'

    - else
      nav.navbar.navbar-expand-sm.p-0
        ul.navbar-nav.mr-auto.d-flex.align-items-center
          li.nav-item class=("current" if current_page?(root_path))
            = link_to root_path(anchor: 'section1'), class: "p-3 headlink toppage"
              = image_tag asset_path("logo.jpg"), class: "logo"

          li.nav-item class=("current" if current_page?(new_user_registration_path))
            = link_to t('Sign up'), new_user_registration_path, class: "p-3 headlink"
          li.nav-item class=("current" if current_page?(new_user_session_path))
            =link_to t('Log in'), new_user_session_path, class: "p-3 headlink"

        ul.navbar-nav.d-flex.align-items-center
          li.nav-item
            = link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class: "p-3 headlink"
          li.nav-item
            == render 'layouts/language'


  body
    == yield